listeners:
  egress_traffic:
    address: 0.0.0.0
    message_format: openai
    port: 12000
    timeout: 30s
llm_providers:
- access_key: $OPENAI_API_KEY
  default: true
  model: gpt-4o-mini
  name: openai/gpt-4o-mini
  provider_interface: openai
- access_key: $OPENAI_API_KEY
  model: gpt-4o
  name: openai/gpt-4o
  provider_interface: openai
  routing_preferences:
  - description: b
    name: code understanding
- access_key: $OPENAI_API_KEY
  model: gpt-4.1
  name: openai/gpt-4.1
  provider_interface: openai
  routing_preferences:
  - description: a
    name: code understanding
tracing:
  random_sampling: 100
version: v0.1.0
