[package]
name = "hermesllm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
serde_with = "3.12.0"
thiserror = "2.0.12"

[dev-dependencies]
async-openai = "0.29.0"
tokio = { version = "1.0", features = ["full"] }
