version: v0.1.0

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o-mini

  - access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o
    default: true

  - access_key: $MISTRAL_API_KEY
    provider_interface: mistral
    model: ministral-3b-latest

  - access_key: $ANTHROPIC_API_KEY
    provider_interface: claude
    model: claude-3-7-sonnet-latest

  - access_key: $ANTHROPIC_API_KEY
    provider_interface: claude
    model: claude-sonnet-4-0

  - access_key: $DEEPSEEK_API_KEY
    provider_interface: deepseek
    model: deepseek-reasoner

  - access_key: $GROQ_API_KEY
    provider_interface: groq
    model: llama-3.1-8b-instant

  - access_key: $GEMINI_API_KEY
    provider_interface: gemini
    model: gemini-1.5-pro-latest

tracing:
  random_sampling: 100
