version: v0.1.0

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:

  - access_key: $OPENAI_API_KEY
    model: openai/gpt-4o-mini

  - access_key: $OPENAI_API_KEY
    model: openai/gpt-4.1

  - access_key: $OPENAI_API_KEY
    model: openai/gpt-4o
    default: true

  - access_key: $ANTHROPIC_API_KEY
    model: anthropic/claude-3-7-sonnet-latest

  - access_key: $ANTHROPIC_API_KEY
    model: anthropic/claude-sonnet-4-0

  - model: zhipu/glm-4.6
    access_key: $ZHIPU_API_KEY

  - model: custom/test-model
    base_url: http://host.docker.internal:11223
    provider_interface: openai

tracing:
  random_sampling: 100
