version: v0.1.0

listeners:
  egress_traffic:
    address: 0.0.0.0
    port: 12000
    message_format: openai
    timeout: 30s

llm_providers:
  - model: openai/gpt-4o-mini
    access_key: $OPENAI_API_KEY
    default: true

  - model: openai/o3
    access_key: $OPENAI_API_KEY

model_aliases:
  arch.summarize.v1:
    target: gpt-4o-mini
  arch.reason.v1:
    target: o3
